version: '3.8'

networks:
  monitoring-net:
    driver: bridge

services:
  # FastAPI Application
  app:
    build: .
    container_name: daraz-app
    ports:
      - "8000:8000"
    user: "root"
    volumes:
      - ./src:/app/src
      - ./models:/app/models
      - ./faiss_index:/app/faiss_index
      - ./my_model:/app/my_model
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - EMBED_MODEL_PATH=/app/my_model
      - HF_HUB_OFFLINE=1
      - TRANSFORMERS_OFFLINE=1
    networks:
      - monitoring-net

  # Prometheus Service (REQUIRED CONFIG)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      # You still need this file!
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring-net

  # Grafana Service (MANUAL CONFIG)
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    # I removed the 'volumes' block here.
    # Now it starts fresh, and you set it up in the browser.
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    user: "root"
    networks:
      - monitoring-net
